pub const FUNCTION_LIST: &[&str] = &[
    "add(a,b)",
    "sub(a,b)",
    "mul(a,b)",
    "div(a,b)",
    "pow(a,b)",
    "tetration(a,b)",
    "root(a,b)",
    "rem(a,b)",
    "negate(x)",
    "factorial(n)",
    "subfactorial(n)",
    "equal(a,b)",
    "notequal(a,b)",
    "greater(a,b)",
    "less(a,b)",
    "greaterequal(a,b)",
    "lessequal(a,b)",
    "and(a,b)",
    "or(a,b)",
    "not(a,b)",
    "sin(t)",
    "cos(t)",
    "tan(t)",
    "asin(x)",
    "acos(x)",
    "atan(x(,y))",
    "sinh(t)",
    "cosh(t)",
    "tanh(t)",
    "asinh(x)",
    "acosh(x)",
    "atanh(x)",
    "ln(x)",
    "exp(x)",
    "min(a,b)",
    "max(a,b)",
    "quadratic(a,b,c)",
    #[cfg(feature = "complex")]
    "cubic(a,b,c,d)",
    #[cfg(feature = "complex")]
    "quartic(a,b,c,d,e)",
    "sqrt(x)",
    "cbrt(x)",
    "sq(x)",
    "cb(x)",
    "sum(start,end(,n),f(n))",
    "prod(start,end(,n),f(n))",
    "gamma(x)",
    "erf(x)",
    "erfc(x)",
    "abs(x)",
    #[cfg(feature = "complex")]
    "arg(x)",
    "recip(x)",
    #[cfg(feature = "complex")]
    "conj(x)",
    "iter(first,steps(,x),f(x))",
    "ceil(x)",
    "floor(x)",
    "round(x)",
    "trunc(x)",
    "fract(x)",
    #[cfg(feature = "complex")]
    "real(x)",
    #[cfg(feature = "complex")]
    "imag(x)",
    "if(cond,then,else)",
    "while(cond,expr(,ret))",
    "fold(start,end,value(,acc)(,k),f(acc,k))",
    "set(value(,x),f(x))",
    "modify(x,new(x)(,f(x)))",
    "exprs(a,b,...)",
    "solve((x,)f(x))",
    #[cfg(feature = "float_rand")]
    "rand_uniform(a,b)",
    #[cfg(feature = "units")]
    "convert(a,b)",
    "numerical_solve(start(,x),f(x))",
    "numerical_derivative(point(,x),f(x))",
    "numerical_integral(start,end(,x),f(x))",
    "numerical_differential(x_0,t_0,t_1(,x,t),f(x,t))",
];
pub fn get_help(str: &str) -> &str {
    match str {
        "add" => "add(a,b), outputs the sum of a and b",
        "sub" => "sub(a,b)",
        "mul" => "mul(a,b)",
        "div" => "div(a,b)",
        "pow" => "pow(a,b)",
        #[cfg(feature = "units")]
        "convert" => "convert(a,b)",
        "tetration" => "tetration(a,b)",
        "root" => "root(a,b)",
        "rem" => "rem(a,b)",
        "negate" => "negate(x)",
        "factorial" => "factorial(n)",
        "subfactorial" => "subfactorial(n)",
        "equal" => "equal(a,b)",
        "notequal" => "notequal(a,b)",
        "greater" => "greater(a,b)",
        "less" => "less(a,b)",
        "greaterequal" => "greaterequal(a,b)",
        "lessequal" => "lessequal(a,b)",
        "and" => "and(a,b)",
        "or" => "or(a,b)",
        "not" => "not(a,b)",
        "sin" => "sin(t)",
        "cos" => "cos(t)",
        "tan" => "tan(t)",
        "asin" => "asin(x)",
        "acos" => "acos(x)",
        "atan" => "atan(x(,y))",
        "sinh" => "sinh(t)",
        "cosh" => "cosh(t)",
        "tanh" => "tanh(t)",
        "asinh" => "asinh(x)",
        "acosh" => "acosh(x)",
        "atanh" => "atanh(x)",
        "ln" => "ln(x)",
        "exp" => "exp(x)",
        "min" => "min(a,b)",
        "max" => "max(a,b)",
        "quadratic" => "quadratic(a,b,c)",
        #[cfg(feature = "complex")]
        "cubic" => "cubic(a,b,c,d)",
        #[cfg(feature = "complex")]
        "quartic" => "quartic(a,b,c,d,e)",
        "sqrt" => "sqrt(x)",
        "cbrt" => "cbrt(x)",
        "sq" => "sq(x)",
        "cb" => "cb(x)",
        "sum" => "sum(start,end(,n),f(n))",
        "prod" => "prod(start,end(,n),f(n))",
        "gamma" => "gamma(x)",
        "erf" => "erf(x)",
        "erfc" => "erfc(x)",
        "abs" => "abs(x)",
        #[cfg(feature = "complex")]
        "arg" => "arg(x)",
        "recip" => "recip(x)",
        #[cfg(feature = "complex")]
        "conj" => "conj(x)",
        "iter" => "iter(first,steps(,x),f(x))",
        "ceil" => "ceil(x)",
        "floor" => "floor(x)",
        "round" => "round(x)",
        "trunc" => "trunc(x)",
        "fract" => "fract(x)",
        #[cfg(feature = "complex")]
        "real" => "real(x)",
        #[cfg(feature = "complex")]
        "imag" => "imag(x)",
        "if" => "if(cond,then,else)",
        "while" => "while(cond,expr(,ret))",
        "fold" => "fold(start,end,value(,acc)(,k),f(acc,k))",
        "set" => "set(value(,x),f(x))",
        "modify" => "modify(new(x),x(,f(x)))",
        "exprs" => "exprs(a,b,...)",
        "solve" => "solve((x,)f(x))",
        #[cfg(feature = "float_rand")]
        "rand_uniform" => "rand_uniform(a,b)",
        "numerical_solve" => "numerical_solve(start(,x),f(x))",
        "numerical_derivative" => "numerical_derivative(point(,x),f(x))",
        "numerical_integral" => "numerical_integral(start,end(,x),f(x))",
        "numerical_differential" => "numerical_differential(x_0,t_0,t_1(,x,t),f(x,t))",
        "" => "",
        _ => "unknown",
    }
    //TODO
}
