pub const FUNCTION_LIST: &[&str] = &[
    "add(a,b)",
    "sub(a,b)",
    "mul(a,b)",
    "div(a,b)",
    "pow(a,b)",
    "tetration(a,b)",
    "root(a,b)",
    "rem(a,b)",
    "negate(a)",
    "factorial(a)",
    "equal(a,b)",
    "notequal(a,b)",
    "greater(a,b)",
    "less(a,b)",
    "greaterequal(a,b)",
    "lessequal(a,b)",
    "and(a,b)",
    "or(a,b)",
    "not(a,b)",
    "sin(t)",
    "cos(t)",
    "tan(t)",
    "asin(x)",
    "acos(x)",
    "atan(x(,y))",
    "sinh(t)",
    "cosh(t)",
    "tanh(t)",
    "asinh(x)",
    "acosh(x)",
    "atanh(x)",
    "ln(x)",
    "exp(x)",
    "min(a,b)",
    "max(a,b)",
    "quadratic(a,b,c)",
    #[cfg(feature = "complex")]
    "cubic(a,b,c,d)",
    #[cfg(feature = "complex")]
    "quartic(a,b,c,d,e)",
    "sqrt(x)",
    "cbrt(x)",
    "sq(x)",
    "cb(x)",
    "sum(start,end(,n),f(n))",
    "prod(start,end(,n),f(n))",
    "gamma(x)",
    "erf(x)",
    "erfc(x)",
    "abs(x)",
    #[cfg(feature = "complex")]
    "arg(x)",
    "recip(x)",
    #[cfg(feature = "complex")]
    "conj(x)",
    "iter(first,steps(,x),f(x))",
    "ceil(x)",
    "floor(x)",
    "round(x)",
    "trunc(x)",
    "fract(x)",
    #[cfg(feature = "complex")]
    "real(x)",
    #[cfg(feature = "complex")]
    "imag(x)",
    "if(cond,then,else)",
    "fold(start,end,value(,acc)(,k),f(acc,k))",
    "set(value(,x),f(x))",
    "modify(value,x,f(x))",
    "solve((x,)f(x))",
];
